In [23]:
sentance = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [24]:
voc_size = 10000

In [37]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [38]:
one_hot_rep = [one_hot(words,voc_size)for words in sentance]
one_hot_rep

[[7130, 6016, 6215, 5314],
 [7130, 6016, 6215, 9596],
 [7130, 79, 6215, 6238],
 [9389, 1007, 4196, 2688, 721],
 [9389, 1007, 4196, 2688, 1185],
 [3652, 7130, 5278, 6215, 736],
 [9127, 1144, 1166, 2688]]

In [39]:
sentance_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7130 6016 6215 5314]
 [   0    0    0    0 7130 6016 6215 9596]
 [   0    0    0    0 7130   79 6215 6238]
 [   0    0    0 9389 1007 4196 2688  721]
 [   0    0    0 9389 1007 4196 2688 1185]
 [   0    0    0 3652 7130 5278 6215  736]
 [   0    0    0    0 9127 1144 1166 2688]]


In [40]:
dim = 10

In [41]:

model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [43]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step


array([[[-1.5044462e-02, -4.1936696e-02,  3.4942850e-03,  1.1825338e-03,
          9.8270401e-03, -1.4754187e-02,  1.1429299e-02, -2.6627136e-02,
          4.5701731e-02,  2.1041904e-02],
        [-1.5044462e-02, -4.1936696e-02,  3.4942850e-03,  1.1825338e-03,
          9.8270401e-03, -1.4754187e-02,  1.1429299e-02, -2.6627136e-02,
          4.5701731e-02,  2.1041904e-02],
        [-1.5044462e-02, -4.1936696e-02,  3.4942850e-03,  1.1825338e-03,
          9.8270401e-03, -1.4754187e-02,  1.1429299e-02, -2.6627136e-02,
          4.5701731e-02,  2.1041904e-02],
        [-1.5044462e-02, -4.1936696e-02,  3.4942850e-03,  1.1825338e-03,
          9.8270401e-03, -1.4754187e-02,  1.1429299e-02, -2.6627136e-02,
          4.5701731e-02,  2.1041904e-02],
        [-2.4362518e-02, -3.5073888e-02, -3.4645103e-02,  1.1374842e-02,
          4.1590776e-02,  6.2940344e-03, -2.9461479e-02,  3.3894848e-02,
          1.0123182e-02, -4.1182220e-02],
        [-1.4137268e-02, -4.2583264e-02,  3.3774819e-02, -4.